# Generated by Django 2.1 on 2018-08-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='temperature_float',
            field=models.FloatField(default=0.0),
        ),
    ]
