# Generated by Django 2.1 on 2018-08-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20180808_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_name',
            field=models.CharField(default='Sensor', max_length=30),
        ),
    ]
