# Generated by Django 2.1 on 2018-08-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_auto_20180808_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computingunit',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
