# Generated by Django 2.1 on 2018-08-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_auto_20180808_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='computingunit',
            name='port_number',
            field=models.IntegerField(default=2000, max_length=4),
        ),
    ]
