# Generated by Django 2.1 on 2018-08-09 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_auto_20180809_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computingunit',
            name='port_number',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
