# Generated by Django 2.1 on 2018-08-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_auto_20180809_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computingunit',
            name='unit_id',
            field=models.AutoField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_id',
            field=models.AutoField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
