# Generated by Django 2.1 on 2018-08-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_auto_20180814_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computingunit',
            name='unit_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
