# Generated by Django 2.1 on 2018-08-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_auto_20180814_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
