# Generated by Django 2.1 on 2018-08-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_auto_20180816_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
